version: 0.2


phases:
  build:
    commands:
    - echo "This is build phase... zipping my website"
  post_build:
    commands:
      - echo "Deployed to s3"
  artifacts:
    files:
      - '**/**'
      
